version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avaliacao
      POSTGRES_DB: avaliacao
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    image: migueljefferson/avaliacao:backend
    environment:
      DB_HOST_NAME: postgres
      DB_PORT: 5432
      DB_NAME: avaliacao
      DB_PASSWORD: avaliacao
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: migueljefferson/avaliacao:frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    deploy:
      replicas: 2
