apiVersion: v1
kind: Pod
metadata: 
  name: frontend-pod
  labels:
    app: frontend
    type: front-end
spec:
  containers:
    - name: frontend
      image: migueljefferson/avaliacao:frontend
      ports:
        - containerPort: 3000