apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
    type: database

spec:
  containers:
    - name: postgres-container
      image: postgres:15.2
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: avaliacao
      ports:
      - containerPort: 5432